defmodule Cheffy.Repo.Migrations.AddExclusionRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:guests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
    end

    create table(:guest_excluded_categories, primary_key: false) do
      add :guest_id,
          references(:guests,
            column: :id,
            name: "guest_excluded_categories_guest_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :ingredient_category_id,
          references(:ingredient_categories,
            column: :id,
            name: "guest_excluded_categories_ingredient_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:guest_excluded_categories, "guest_excluded_categories_guest_id_fkey")

    drop constraint(
           :guest_excluded_categories,
           "guest_excluded_categories_ingredient_category_id_fkey"
         )

    drop table(:guest_excluded_categories)

    drop table(:guests)
  end
end
