defmodule Cheffy.Repo.Migrations.InitialResourceMigrations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:recipes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
    end

    create table(:recipe_components, primary_key: false) do
      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "recipe_components_recipe_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :ingredient_id, :uuid, null: false, primary_key: true
    end

    create table(:ingredients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:recipe_components) do
      modify :ingredient_id,
             references(:ingredients,
               column: :id,
               name: "recipe_components_ingredient_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:ingredients) do
      add :name, :text, null: false
      add :ingredient_category_id, :uuid, null: false
    end

    create table(:ingredient_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ingredients) do
      modify :ingredient_category_id,
             references(:ingredient_categories,
               column: :id,
               name: "ingredients_ingredient_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:ingredient_categories) do
      add :name, :text, null: false
    end
  end

  def down do
    alter table(:ingredient_categories) do
      remove :name
    end

    drop constraint(:ingredients, "ingredients_ingredient_category_id_fkey")

    alter table(:ingredients) do
      modify :ingredient_category_id, :uuid
    end

    drop table(:ingredient_categories)

    alter table(:ingredients) do
      remove :ingredient_category_id
      remove :name
    end

    drop constraint(:recipe_components, "recipe_components_ingredient_id_fkey")

    alter table(:recipe_components) do
      modify :ingredient_id, :uuid
    end

    drop table(:ingredients)

    drop constraint(:recipe_components, "recipe_components_recipe_id_fkey")

    drop table(:recipe_components)

    drop table(:recipes)
  end
end
